version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go mod download
      - run:
          command: go test -v ./...
          environment:
            TF_ACC: 1
